global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'cyborg-monitor'

scrape_configs:
  - job_name: 'cyborg-api'
    static_configs:
      - targets: ['cyborg-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
