global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'cyborg-rl-trainer'
    static_configs:
      - targets: ['trainer:8000']
    metrics_path: /metrics

  - job_name: 'cyborg-rl-trainer-minerl'
    static_configs:
      - targets: ['trainer-minerl:8001']
    metrics_path: /metrics
